### ISSUE TITLE
wing's shadow and circle behavior

### ISSUE THREAD

**Issue by 435352980** [flowtsohg/mdx-m3-viewer#25]
Find some strange behavior on latest model viewer.
There are many mosaics in team color 
![F}FSE(R %NULUN_2~MJIV25](https://user-images.githubusercontent.com/35485428/65258250-29a5eb80-db35-11e9-9866-9c2d5c633a8f.png)
Maybe a circle renderer bug？
![}5MRPIYKICNVDO WNSMSZRK](https://user-images.githubusercontent.com/35485428/65258851-3b3bc300-db36-11e9-8e40-8be35fc87e91.png)
Also with some wings
![SZK%7 ZX@J6D_631~CJK} U](https://user-images.githubusercontent.com/35485428/65258921-59a1be80-db36-11e9-986d-2ac9c135a6fc.png)
![}A)LN0PF2@_6_F5}P0ZLGK3](https://user-images.githubusercontent.com/35485428/65258962-70481580-db36-11e9-95a5-9964a1b95127.png)

I find it can injiet some model befor create an instance by add a model on attachments manually.
and can it support multi?
```js
    model.whenLoaded().then(model => {
     // use this code before add instance
     model.attachments[1].internalModel = viewer.load(`${name}.mdx`, pathSolver);

      let instance = model.addInstance();
      instance.setScene(scene);
      instance.setSequence(
        model.sequences.findIndex(seq => seq.name.toLowerCase().includes('stand')),
      );
    });
```

**Comment by flowtsohg** [comment]
Thanks for reporting the team glows issue, I have a local fix, which I'll hopefully commit in a day or two with more updates.

I am not quite sure what you mean with that piece of code and question. You can freely load any model you want wherever you want, and create instances of it, and you can attach those instances to nodes (which attachments are) via `ModelInstance.setParent()`.
The internal model attachments are used to load attachments that are specified in the MDX file itself, for example those used by Undead and Nightelf buildings when they are being built.

**Comment by flowtsohg** [comment]
Should be fixed now, however I am still unsure about your question.

**Comment by 435352980** [comment]
Thanks, I tried to do it the way you said, It works!
Team color is normal now, but shadow is still have.
Here are the wing's models i test.
[Wing01.zip](https://github.com/flowtsohg/mdx-m3-viewer/files/3638084/Wing01.zip)
[FairyBlessing.zip](https://github.com/flowtsohg/mdx-m3-viewer/files/3638085/FairyBlessing.zip)

**Comment by flowtsohg** [comment]
The wing model not showing all of those chunks suggests there is some alpha test also for additive layers, but unfortunately I can't seem to run any wc3 version whatsoever anymore using GL.
Aside from that, it also seems like the geoset alpha should be used differently for additive.
I have a fix that makes it look ok, but I want to test it some more. Who knows how it will affect other models.

For the fairies, do you mean the small line that follows the last ribbon? if so, I know about it, maybe I'll look at solving it again.
If you mean something else, I am not sure. I compared to how WE renders the model and it's pretty close.

**Comment by 435352980** [comment]
Yes, the line.

**Comment by 435352980** [comment]
looks like the neweast version missing some textures
[Gilgamesh.zip](https://github.com/flowtsohg/mdx-m3-viewer/files/3639035/Gilgamesh.zip)
version 4.7.0
![4 7 0](https://user-images.githubusercontent.com/35485428/65378659-3de11880-dcee-11e9-8a88-5d4a1a3008c7.png)
version 4.7.1
![4 7 1](https://user-images.githubusercontent.com/35485428/65378662-40437280-dcee-11e9-8f0f-2f7a47b86aee.png)

**Comment by flowtsohg** [comment]
Yes, I see why, will be fixed in the next commit.

**Comment by flowtsohg** [comment]
Incidentally, the proper handling of alphas finally made the Paladin hammer ribbons be in the right color, something which I never could figure in the past 👍
