### ISSUE TITLE
BindPose is float32[12] and not float32[16]

### ISSUE THREAD

**Issue by Ralle** [flowtsohg/mdx-m3-viewer#32]
Change this line:
https://github.com/flowtsohg/mdx-m3-viewer/blob/684784721da5e5fe0544a46258034e60025506c4/src/parsers/mdlx/model.js#L284

To be arrays of 12.

**Comment by flowtsohg** [comment]
This was fixed in the v5-beta branch in commit 7011acbe0cad1195ee1b948c90e1b9af84ab69a6
