### ISSUE TITLE
Animation map: PRE2 Width and Length MDL tokens switched

### ISSUE THREAD

**Issue by EzraZebra** [flowtsohg/mdx-m3-viewer#39]
https://github.com/flowtsohg/mdx-m3-viewer/blob/2572174e9bd4b68208d1d9c16d48d8bccec3e866/src/parsers/mdlx/animationmap.ts#L47

KP2N has the model token Width and KP2W the token Length, shouldn't that be the other way around?

**Comment by flowtsohg** [comment]
There were many confusions with these two values over the years.
I won't say I really remember who said what, but ultimately the viewer is using KP2N for the X axis, and KP2W for the Y axis.
I believe these names should be changed. I don't know who came up with the terms originally (Magos?) however they are not intuitive.

**Comment by EzraZebra** [comment]
Ah, I see, I guess I shouldn't have expected to be so straightforward :P

**Comment by flowtsohg** [comment]
You made me look at the parser and it actually still reads/writes the animations swapped in the MDL part, gotta fix that.

**Comment by flowtsohg** [comment]
Solved in beta.22 but forgot to reference the issue 🤷‍♀
