### ISSUE TITLE
Material priorityPlane Mdx read/write type mismatch (int32 <> uint32)

### ISSUE THREAD

**Issue by EzraZebra** [flowtsohg/mdx-m3-viewer#40]
The priorityPlane is being read as int32 but written as uint32. It probably doesn't matter, but thought I'd point it out :)

https://github.com/flowtsohg/mdx-m3-viewer/blob/3c94d049d76ee6f15d938f3020ccd777b66ce83d/src/parsers/mdlx/material.ts#L20

https://github.com/flowtsohg/mdx-m3-viewer/blob/3c94d049d76ee6f15d938f3020ccd777b66ce83d/src/parsers/mdlx/material.ts#L40

**Comment by flowtsohg** [comment]
Will be fixed whenever I'll commit again, thanks 👍
