### ISSUE TITLE
MDLX Parser ParticleEmitter: writeMdl writes path with writeAttrib instead of writeStringAttrib

### ISSUE THREAD

**Issue by EzraZebra** [flowtsohg/mdx-m3-viewer#43]
https://github.com/flowtsohg/mdx-m3-viewer/blob/eef5dd3889b7adbf268e4ea7ba812995d6d5c74c/src/parsers/mdlx/particleemitter.ts#L140

**Comment by flowtsohg** [comment]
Thanks, will be fixed in the next commit.
