### ISSUE TITLE
MDLX Parser: writeMdx tangents & skin: write size?

### ISSUE THREAD

**Issue by EzraZebra** [flowtsohg/mdx-m3-viewer#45]
https://github.com/flowtsohg/mdx-m3-viewer/blob/eef5dd3889b7adbf268e4ea7ba812995d6d5c74c/src/parsers/mdlx/geoset.ts#L149

Shouldn't the size of the tangents and skin be written there?
In `readMdx` the sizes are being read, so it seems like it can be written too.

**Comment by flowtsohg** [comment]
Thanks, will be fixed the next commit.
