### ISSUE TITLE
Layer flags mistake?

### ISSUE THREAD

**Issue by EzraZebra** [flowtsohg/mdx-m3-viewer#46]
https://github.com/flowtsohg/mdx-m3-viewer/blob/b7fb09f4c9a3812d5298cd3cb274b217338c6788/src/parsers/mdlx/layer.ts#L107

According to your [MDX Specs post on Hive](https://www.hiveworkshop.com/threads/mdx-specifications.240487/) `0x30` is no depth test and `0x40` is no depth set, while here it's `0x40` and `0x100` respectively.
According to [this MDL dump of a Reforged model](https://www.hiveworkshop.com/threads/retera-model-studio-reforged-hack.320070/page-2#post-3387392) it's `0x40` and `0x80` respectively, and `0x100` for a new Unlit flag.

Any idea which is correct?

**Comment by flowtsohg** [comment]
That is an error in the specs, should indeed be 0x40 and 0x80, that's how bitwise flags work 
Funnily the MDX handler is using the flags correctly, not sure how I added the wrong value in the newer MDL parser 😛

**Comment by EzraZebra** [comment]
> that's how bitwise flags work
That's what I thought, but I wasn't sure :P 
> not sure how I added the wrong value in the newer MDL parser stuck_out_tongue
Mistakes happen :P It's pretty amazing how few there are tbh.
