### ISSUE TITLE
Fix read me

### ISSUE THREAD

**Issue by arcman7** [flowtsohg/mdx-m3-viewer#53]
## Docs right now - 
For example:
```
viewer.on('error', (viewer, error, reason) => {
  console.log(`Error: ${error}, Reason: ${reason}`);
});
```
In addition there is ModelViewer.whenAllLoaded() which will trigger both on the idle event, and if there is currently nothing loading.

## Should be -
For example:
```
viewer.on('error', ({ viewer, error, reason }) => {
  console.log(`Error: ${error}, Reason: ${reason}`);
});
```
In addition, there is ModelViewer.whenAllLoaded() which will trigger both on the idle event, and if there is currently nothing loading.

**Comment by flowtsohg** [comment]
True, however the recent changes mean that different event objects can have different properties, depending on why they were emitted, so I changed it to a simple `e` as is normally the notation with JS event listeners.

**Comment by arcman7** [comment]
Np! Love the work that you and @d07RiV have done so far. 

Hey btw, any chance you know why my rendering is so blurry?
![image](https://user-images.githubusercontent.com/9598327/100807820-d80b1900-33e7-11eb-9946-848180d88a02.png)

I created a gist to demo the most basic rendering of a grunt, but for whatever reason, it always renders with a blurry resolution.

**Comment by flowtsohg** [comment]
Ensure that your canvas back buffer is big enough, i.e. `canvas.width` and `canvas.height` rather than CSS things such as `canvas.clientWidth` and `canvas.clientHeight` (or via a style or whatever).
I typically resize the canvas' back buffer to whatever the CSS size is automatically in a `resize` event listener, but this may not fit your needs.

Just a small note - `Resource.ok` doesn't exist anymore, due to the change to promises. If a resource failed to load, the promise will resolve to undefined, so e.g. `if (model) { }` instead of `if (model.ok) { }`.

**Comment by arcman7** [comment]
Oh nice, I didn't realize I could add literal pixels by increasing the dimensions of the canvas element directly. 

I appreciate your tips! I just started digging into this code. The camera implementation example is perfect for me.

As far as the camera animations go, if you're referring to the `requestAnimationFrame(callback)` function, yeah that's how I'm able to view the model from all angles just by clicking and scrolling around with the mouse. I got that from @d07RiV's website code. It works pretty smoothly as far as I can tell. 

I made the changes you suggested. I'll add a little more boilerplate code such that it starts up a localhost server via python or node, and contains the file assets needed to render the model (if that's legal). And then I'll make a PR. No worries if you don't want it in here on this repo, I figured it's just an option to help newbs like me get up and running.

**Comment by flowtsohg** [comment]
I meant the MDX camera animated properties, I never actually tested them, don't know even which models have animated cameras.

I get the feeling you didn't notice the [clients](https://github.com/flowtsohg/mdx-m3-viewer/tree/master/clients) in the repo, they kinda act as examples that can run with the given http-server.js, with some of them actually being used on the hiveworkshop.
Their code is messy and bad, but it does hopefully show different aspects of the library being used.

As far as putting stuff on github, any Blizzard owned resources are out of the question.
With that being said, if you check the clients, you'll see they have a place to get game files from, just sayin' :P

**Comment by arcman7** [comment]
Ah, okay, yes I hadn't actually checked out what was in that directory or read the readme. You have so much stuff! This repo is the gift that keeps on giving. I'll continue on, and if I see room for anything I might be able to add or improve I'll make a pr. Thanks again for being so helpful!
