### ISSUE TITLE
Viewer is just black for me

### ISSUE THREAD

**Issue by Ralle** [flowtsohg/mdx-m3-viewer#55]
Hey Chananya,

The viewer code that used to work isn't working anymore. The screen is just black.

The only thing that sticks out to me is that it always has this error:

```
error: "Failed to fetch a generic resource"
​fetchUrl: "/casc-contents?path=UI%5CSoundInfo%5CAnimLookups.slk"
​viewer: Object { _eventsCount: 4, frameTime: 16, visibleCells: 1, … }
```

But it did so in the past and that file does not exist. Perhaps the promise thing caused it to not work any longer?

The network tab shows that it is loading all these things:
<img width="687" alt="image" src="https://user-images.githubusercontent.com/467309/102265683-bba6ca80-3f17-11eb-995d-56725e59d860.png">

I would show you the code but not in a ticket and your email seems broken.

**Comment by Ralle** [comment]
I found the error. model.ok is probably deprecated.

**Comment by flowtsohg** [comment]
`Model.ok` is indeed not used anymore, only compare against the resources themselves (which will be undefined if any issue occured).
With that being said, you also seem to have some issue when resizing the window, not sure what's up with that.

The sound SLK is gone in Reforged, hence you will forever get that error as long as the code isn't updated to handle Reforged correctly.

**Comment by Ralle** [comment]
Oh well. It works now and I am happy. Thanks :)
