### ISSUE TITLE
(Question) Adding arbitrary units/models to an already loaded map

### ISSUE THREAD

**Issue by arcman7** [flowtsohg/mdx-m3-viewer#56]
If I want to render, say a sphere, into an already loaded + rendered wc3 map, what would be the most appropriate way to go about this?

Looking at the code in `mdx-m3-viewer\src\viewer\handlers\w3x\viewer.ts` lines 627-656:
```
for (let unit of unitsDoo.units) {
      let row: MappedDataRow | undefined;
      let path;

      // Hardcoded?
      if (unit.id === 'sloc') {
        path = 'Objects\\StartLocation\\StartLocation.mdx';
      } else {
        row = this.unitsData.getRow(unit.id);

        path = <string>row.file;

        if (path.endsWith('.mdl')) {
          path = path.slice(0, -4);
        }

        path += '.mdx';
      }

      if (path) {
        this.load(path)
          .then((model) => {
            if (model) {
              this.units.push(new Unit(this, <MdxModel>model, row, unit));
            }
          });
      } else {
        console.log('Unknown unit ID', unit.id, unit);
      }
    }
```
    
It looks like I can just add units/objects to the map like so -
```
    if (model) {
        this.units.push(new Unit(this, <MdxModel>model, row, unit));
    }
```
given that I provide -
  * a model class
  * stub object for `unit` that holds info such as scale, location, angle, player, etc.
  * stub object for `row`
  * a model instance class that implements the `setScene` method

My understanding is that the model should be able to create a model instance and is in charge of determining what webgl program to use to render itself. I would start off by using an existing primitive such as a sphere.

**Comment by flowtsohg** [comment]
You can always load any models you want and add instances of them anywhere you want, regardless of whether it's the normal viewer or the map one.

If the viewer had more game logic and `Unit` actually meant something, you'd probably have to adapt your data to it, but right now `Unit` is pretty meaningless, just a way to partition the code - all the constructor really does is create a new instance, and set its basic state like location and team colors.

In general the viewer has `Model` which knows how to parse the needed files/data and construct geometry, animation data, etc.
Then there is `ModelInstance` which references the model, and has state like time, which animation is running, team color, etc.
Finally `Scene` stores a bunch of instances, and tells them to update and render.

If you are interested in primitive meshes, there was previously the `GEO` handler which handled them, which was recently deleted and replaced with a MDLX primitive generator.
That is, you use the [createPrimitive](https://github.com/flowtsohg/mdx-m3-viewer/blob/master/src/utils/mdx/primitives/createprimitive.ts) function which generates an `MdlxModel`, which you can then load directly in the viewer as MDX.
You can check the [relevant unit tests](https://github.com/flowtsohg/mdx-m3-viewer/blob/master/clients/tests/mdxprimitives.js) to see some calls to it.

**Comment by arcman7** [comment]
So I have been been able to add a single sphere primitive into a map (loaded on the clients/map/index when running npm serve) like so:
```
window.viewer = viewer // I dont know why, but the viewer reference does not start off belonging to window,
let texture = viewer.load('textures/shockwave_ice1.blp');
let spherePrimitive = ModelViewer.utils.mdx.primitives.createSphere(20,20,20);
(async()=> {
let sphereModel = await ModelViewer.utils.mdx.createPrimitive(viewer, spherePrimitive , { texture });
let sphereInstance = sphereModel .addInstance();
let Unit = Object.getPrototypeOf(viewer.units[0]).constructor;
let testUnitInfo = { "location":[0,0,100],"rotation":[0,0,0,1],"player":0,"scale":[1,1,1] };
viewer.units.push(new Unit(viewer, sphereModel , undefined, testUnitInfo ));
viewer.scenes[0].addInstance(sphereInstance);
}();
```

The sphere shows up at the coordinates [0,0,0] despite being set to [0,0,100], and it will never leave that location. I've tried calling update on it like so:
```
sphereInstance.update(); // 1st attempt
sphereInstance.update(sphereInstance.updateFrame + 1, viewer.scenes[0]); // 2nd attempt

But it still doesn't move? I feel like there's a different update or render function I'm supposed to use.

**Comment by flowtsohg** [comment]
You don't actually need the fake `Unit` stuff.

Either way, you are correct that it's not working, because the new code seems to be bugged, gotta look at it more closely.

**Comment by flowtsohg** [comment]
I believe it should work now correctly. You don't need to manually call `update`.
You should probably prefer `viewer.worldScene` than `viewer.scenes[0]`, but I guess that will only matter if the viewer is worked on...

**Comment by arcman7** [comment]
Oh nice! Yes, it definitely works. I'll start using `worldScene` then as you suggest.

**Comment by arcman7** [comment]
Still visiting with the fam, but that last commit - #54 - definitely works. Excited to get back to this once I leave.

**Comment by arcman7** [comment]
Back from visiting the fam. 

Another question - in `mdx-m3-viewer\src\viewer\handlers\mdx\model.ts` the property `collisionShapes: CollisionShape[] = [];` is declared - can I use these values for a physics engine? My guess is that they are representative of the model shapes being used in 3d space.

**Comment by flowtsohg** [comment]
I am not sure what you mean by use. Many models don't have collision shapes, and those that do are not accurate. I don't even remember what the game uses them for 🤔

**Comment by arcman7** [comment]
Hmm, I guess I'll have to test them out on a per-case-basis. In the meantime, I hear cylinders are good approximations of humanoids lol

**Comment by flowtsohg** [comment]
It works for thousands of badly made UE4/Unity games, could work for you :D

**Comment by arcman7** [comment]
Is there a way to extract heightmap data from the `viewer.heightMap` property once the map has loaded?

 I don't know what format or how the data is encoded in the webgl texture object, but I'm looking a way to either access directly or derive values from that height map in the following format:
 ```
 				var heightFieldShape = new Ammo.btHeightfieldTerrainShape(
					terrainWidth,
					terrainDepth,
					heightData,  // the most important values
					heightScale,
					terrainMinHeight,
					terrainMaxHeight,
					upAxis,
					hdt,
					flipQuadEdges
				);
```

**Comment by flowtsohg** [comment]
The heights are not stored on the client, but [calculating them](https://github.com/flowtsohg/mdx-m3-viewer/blob/master/src/viewer/handlers/w3x/viewer.ts#L389) is quite simple.

With that being said, note that those are solely for the ground geometry and don't take cliffs/ramps into consideration.

There is a `heightAt()` function, but I see that it's commented out, not sure why. Probably because it too doesn't take cliffs/ramps into consideration.

**Comment by arcman7** [comment]
I see... to be clear does the texture object include the cliff height data or just the terrain?

**Comment by flowtsohg** [comment]
No, as you can see in the link above, they are in a separate texture.
They are also used differently - getting the height of the terrain geometry is a bilinear interpolation of the 4 vertices of a specific cell (which you can see in `heightAt()`, or in the terrain shader).
Getting the proper in-game height...I am not actually sure, were there per-model height maps? does the game calculate them at load time for each cliff model? what about cliff/terrain doodads?
In the terrain shader this is handled naturally by it knowing all of the vertex positions and their interpolations, but the question is how to do that efficiently in JS.

**Comment by arcman7** [comment]
> height of the terrain geometry is a bilinear interpolation of the 4 vertices of a specific cell

Do the four vertices form two triangles? Otherwise, I can't see a way to interpolate the height from four coordinates.
I also see this in the commented out code of the `heightAt` function:
```
 let triZ0 = heightMap[minY][minX],
        triZ1 = heightMap[minY][maxX],
        triZ2 = heightMap[maxY][minX],
        triZ3 = heightMap[maxY][maxX],
        sqX = x - minX,
        sqZ = y - minY,
        height;

      if ((sqX + sqZ) < 1) {
        height = triZ0 + (triZ1 - triZ0) * sqX + (triZ2 - triZ0) * sqZ;
      } else {
        height = triZ3 + (triZ1 - triZ3) * (1 - sqZ) + (triZ2 - triZ3) * (1 - sqX);
      }
```

If that is the case, then I'll just use this function as is in my own code :)

**Comment by flowtsohg** [comment]
Yes, each cell is a square made of two triangles.

I could clean it a bit and uncomment, but I am not sure how useful it is without being the real height.

**Comment by flowtsohg** [comment]
Also I just realized that uses `heightMap`, from the time the height values were saved on the client. But you can look at `groundNormal` just above it 😂

**Comment by arcman7** [comment]
![image](https://user-images.githubusercontent.com/9598327/106203108-c2a83600-616f-11eb-8c3f-89a91e9c4cd3.png)
Haha, thank you!

And now onwards to learn about pathing algorithms

**Comment by flowtsohg** [comment]
For that you have `war3map.wpm` (and the matching `War3MapWpm` class).
If I remember correctly it contains 4x4 cells per terrain cell, with each cell being a flags byte saying what kind of pathing is activated (walk, build, fly, err...were there more?)
You can always map to a cell with an instance's position relative to the map's origin, and some simple math.
From there apply whatever algorithm, typically A*.

**Comment by arcman7** [comment]
Ohh, okay. I've heard of the A* algo, but never had a chance to use it in any of my projects. This is gonna be fun. 

> (walk, build, fly, err...were there more?)
Lol. Maybe tunneling? I'll keep it simple to start with.

> For it to be really correct you'd need also to take instance sizes (e.g. via their bounds) into account and such, but yeah at that point research pathing in general :P

Yeah, I figure I'll do some reading after my first naive solution.

**Comment by flowtsohg** [comment]
I recommend reading [this tutorial](https://www.redblobgames.com/pathfinding/a-star/introduction.html) and other relevant pages on that site, it has been very useful to me in the past.

**Comment by arcman7** [comment]
Dude, check this out!
https://www.loom.com/share/89621f866fc746d88facbcf6be783c80

I got physics to work! I've also got 3d terrain pathing working atm. I'm gonna set up a silly soccer game demo soon, I'll add that in the example clients if you're interested :p

**Comment by flowtsohg** [comment]
Heh, that's pretty cool.
Looks like Box2D's API, so probably Bullet? never used it so not sure how it looks.

It's not really related to WC3 so I don't know about adding this to the repo.
It would be neat to have a list of external references to clients/code other people made, but I am not sure how many of those exist or whether they'll continue existing at the same addresses 🤔

**Comment by arcman7** [comment]
> Looks like Box2D's API, so probably Bullet?

Yes, it is Bullet physics ported to javascript, they call that ported version [Bullet Ammo.js](https://github.com/kripken/ammo.js/) (**a**voided **m**aking **m**y **o**wn js physics engine).

> It would be neat to have a list of external references to clients/code other people made

Yeah, it would be hard to track them down, but it's never too late to start. Totally optional though, I just figured it would be a way to showcase the fun things you can do with your repo.
