### ISSUE TITLE
how  can use War3Map make extract w3x file to a dir?

### ISSUE THREAD

**Issue by qq1053831109** [flowtsohg/mdx-m3-viewer#59]
how  can use War3Map make extract w3x file to a dir?

**Comment by flowtsohg** [comment]
Typically if you are talking about a standard map that wasn't optimized/protected, you can loop over all of the internal files, get their buffers, and from there you are free to do whatever you want, e.g. save the buffers to files if you are using Node.

E.g.:
```ts
for (let name of map.getFileNames()) {
    let file = map.get(name);
    let buffer = file.arrayBuffer(); // an ArrayBuffer

    fs.appendFile(path, Buffer.from(buffer));
});
}
```
