### ISSUE TITLE
Fix client examples

### ISSUE THREAD

**Issue by arcman7** [flowtsohg/mdx-m3-viewer#67]
In file `mdx-m3-viewer/clients/shared/localorhive.js`

Change line 12 to:
```
return `https://www.hiveworkshop.com/casc-contents?path=${src}`;
```

For me, that beta URL stopped working when making a request from the browser on a localhost URL.

**Comment by flowtsohg** [comment]
It's already changed on my local copy, just didn't commit yet.
Hive was updated, so it's no longer beta :)

**Comment by arcman7** [comment]
Awesome. I figured you already knew, just wanted the visibility on this issue for anyone else that was experiencing it. All those CORS rejection errors in the console were scary! 😆

**Comment by flowtsohg** [comment]
I am too used to CORS errors at this point :P

I asked Ralle to CORS-enabled the 404 page, so at least now it's easier to see if the result is actual CORS or the url is just wrong.

**Comment by arcman7** [comment]
Haha, that's great if he does.
