### ISSUE TITLE
Heya!

### ISSUE THREAD

**Issue by arcman7** [flowtsohg/mdx-m3-viewer#80]
It's been awhile, but as I learned more about what I was doing I eventually decided to make the switch over to babylon js.

I wanted to swing by here and drop a line about [AssemblyScript](https://www.assemblyscript.org/).

I recall you mentioning how hard it would be to port everything to wasm, but this makes it easy. The procedure in this guide makes this look very approachable:
https://www.fastly.com/blog/porting-javascript-or-typescript-to-assemblyscript

Btw, here's my project I'm still working on:
https://g7r7sz.colyseus.dev/client/index.html

Still have a ways to go, but I enjoy doing it very much.

**Comment by ilimei** [comment]
👍
